export const THEMES: Record<string, string[]> = {
  MOVIES: [
    "The Godfather",
    "The Shawshank Redemption",
    "Forrest Gump",
    "The Matrix",
    "Interstellar",
    "Inception",
    "Fight Club",
    "Pulp Fiction",
    "Inglourious Basterds",
    "Django Unchained",
    "The Lord of the Rings",
    "Star Wars",
    "The Dark Knight Trilogy",
    "Gladiator",
    "Titanic",
    "Avatar",
    "Jurassic Park",
    "Back to the Future",
    "Terminator",
    "Alien",
    "Blade Runner",
    "Mad Max",
    "The Wolf of Wall Street",
    "Schindler’s List",
    "Goodfellas",
    "Scarface",
    "The Silence of the Lambs",
    "Psycho",
    "The Shining",
    "Parasite",
    "City of God",
    "Elite Squad",
    "Central Station",
    "A Dog’s Will",
    "WALL·E",
    "Toy Story",
    "Finding Nemo",
    "Inside Out",
    "Up",
    "Spider-Man: Into the Spider-Verse",
    "The Avengers",
    "Iron Man",
    "Captain America",
    "Doctor Strange",
    "Guardians of the Galaxy",
    "Joker",
    "Logan",
    "Saving Private Ryan",
    "Life Is Beautiful",
    "The Pianist",
    "Rocky",
    "Rambo",
    "Indiana Jones",
    "The Sixth Sense",
    "The Departed",
    "The Big Lebowski",
    "The Truman Show",
    "Her",
    "Ex Machina",
    "Gravity",
    "District 9",
    "Donnie Darko",
    "Amélie",
    "Spirited Away",
    "Princess Mononoke",
    "Akira",
  ],

  SERIES: [
    "Breaking Bad",
    "Better Call Saul",
    "Game of Thrones",
    "House of the Dragon",
    "Dark",
    "Stranger Things",
    "The Office",
    "Friends",
    "The Boys",
    "Black Mirror",
    "Westworld",
    "Mr. Robot",
    "Narcos",
    "Money Heist",
    "Peaky Blinders",
    "Sherlock",
    "The Mandalorian",
    "Loki",
    "Arcane",
    "Attack on Titan",
    "Death Note",
    "One Piece (Live Action)",
    "The Last of Us",
    "Chernobyl",
    "Dexter",
    "Vikings",
    "Suits",
    "How I Met Your Mother",
    "Rick and Morty",
    "BoJack Horseman",
    "True Detective",
    "The Witcher",
    "Prison Break",
    "Lost",
    "The Crown",
    "Ozark",
    "The Handmaid’s Tale",
    "The Expanse",
    "The Umbrella Academy",
    "The Flash",
    "Arrow",
    "Supernatural",
    "Lucifer",
    "Gotham",
    "Daredevil",
    "Jessica Jones",
    "Luke Cage",
    "Iron Fist",
    "The Punisher",
    "The Defenders",
  ],

  VIDEO_GAMES: [
    "The Legend of Zelda",
    "Super Mario Bros.",
    "Minecraft",
    "Fortnite",
    "Call of Duty",
    "Grand Theft Auto (GTA)",
    "Red Dead Redemption",
    "The Witcher",
    "Cyberpunk 2077",
    "Overwatch",
    "League of Legends",
    "Dota",
    "Apex Legends",
    "Valorant",
    "Among Us",
    "Animal Crossing",
    "Halo",
    "God of War",
    "Final Fantasy",
    "Resident Evil",
    "Silent Hill",
    "Metal Gear Solid",
    "Tomb Raider",
    "Assassin's Creed",
    "Dark Souls",
    "Elden Ring",
    "FIFA",
    "Madden NFL",
    "NBA 2K",
    "The Sims",
    "Fall Guys",
    "Rocket League",
    "Destiny",
    "Borderlands",
    "Mass Effect",
    "Star Wars Jedi: Fallen Order",
    "Horizon Zero Dawn",
    "Death Stranding",
    "Ghost of Tsushima",
    "Splatoon",
    "Persona 5",
    "Cuphead",
    "Hades",
    "Genshin Impact",
    "Valorant",
    "Rainbow Six Siege",
    "Sea of Thieves",
    "No Man's Sky",
    "Stardew Valley",
    "Celeste",
    "Hollow Knight",
    "Sekiro: Shadows Die Twice",
    "Batman: Arkham Series",
    "Spider-Man",
    "Hytale",
  ],

  FIC_CHARACTERS: [
    "Harry Potter",
    "Hermione Granger",
    "Ron Weasley",
    "Frodo Baggins",
    "Gandalf",
    "Aragorn",
    "Katniss Everdeen",
    "Peeta Mellark",
    "Jon Snow",
    "Daenerys Targaryen",
    "Tyrion Lannister",
    "Walter White",
    "Jesse Pinkman",
    "Sherlock Holmes",
    "Dr. John Watson",
    "Tony Stark",
    "Steve Rogers",
    "Bruce Wayne",
    "Clark Kent",
    "Darth Vader",
    "Luke Skywalker",
    "Yoda",
    "Indiana Jones",
    "James Bond",
    "Lara Croft",
    "Mario",
    "Link",
    "Samus Aran",
    "Master Chief",
    "Solid Snake",
    "Geralt of Rivia",
    "Ciri",
    "Yennefer",
    "Ezio Auditore",
    "Altair Ibn-La'Ahad",
    "Cloud Strife",
    "Sephiroth",
    "Tifa Lockhart",
    "Aerith Gainsborough",
    "Kratos",
    "Atreus",
    "Ellie (The Last of Us)",
    "Joel (The Last of Us)",
    "Michael De Santa (Grand Theft Auto V)",
    "Franklin Clinton (Grand Theft Auto V)",
    "Trevor Philips (Grand Theft Auto V)",
    "Aloy (Horizon Zero Dawn)",
    "Nathan Drake (Uncharted)",
    "Chun-Li (Street Fighter)",
    "Ryu (Street Fighter)",
    "Scorpion (Mortal Kombat)",
    "Sub-Zero (Mortal Kombat)",
  ],

  PEOPLE: [
    "Albert Einstein",
    "Marie Curie",
    "Isaac Newton",
    "Leonardo da Vinci",
    "Galileo Galilei",
    "Charles Darwin",
    "Nikola Tesla",
    "Stephen Hawking",
    "Ada Lovelace",
    "Rosalind Franklin",
    "Martin Luther King Jr.",
    "Mahatma Gandhi",
    "Nelson Mandela",
    "Winston Churchill",
    "Abraham Lincoln",
    "George Washington",
    "Queen Elizabeth II",
    "Cleopatra",
    "Julius Caesar",
    "Alexander the Great",
    "Joan of Arc",
    "Florence Nightingale",
    "Mother Teresa",
    "Amelia Earhart",
    "Frida Kahlo",
    "Pablo Picasso",
    "Vincent van Gogh",
    "Wolfgang Amadeus Mozart",
    "Ludwig van Beethoven",
    "William Shakespeare",
    "Mark Twain",
    "Charles Dickens",
    "Jane Austen",
    "Ernest Hemingway",
    "Friedrich Nietzsche",
    "Sigmund Freud",
    "Carl Jung",
    "Michelangelo",
    "Raphael",
    "Donatello",
    "Socrates",
    "Plato",
    "Aristotle",
    "Anitta",
    "Pelé",
    "Neymar",
    "Ayrton Senna",
    "Gisele Bündchen",
    "Carmen Miranda",
    "Oscar Niemeyer",
    "Jorge Amado",
    "Cazuza",
    "Chico Buarque",
    "Caetano Veloso",
    "Gilberto Gil",
    "Tom Jobim",
    "Vinicius de Moraes",
    "Heitor Villa-Lobos",
    "Joaquim Nabuco",
    "Tiradentes",
    "Zumbi dos Palmares",
    "Billie Eilish",
    "Elon Musk",
    "Steve Jobs",
    "Bill Gates",
    "Mark Zuckerberg",
    "Jeff Bezos",
    "Oprah Winfrey",
    "Walt Disney",
    "Charlie Chaplin",
    "Marilyn Monroe",
    "Audrey Hepburn",
    "James Dean",
    "Bruce Lee",
    "Muhammad Ali",
    "Serena Williams",
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Roger Federer",
    "Rafael Nadal",
    "Usain Bolt",
    "Michael Phelps",
    "Tom Holand",
    "Robert Downey Jr.",
    "Scarlett Johansson",
    "Chris Hemsworth",
    "Chris Evans",
    "Jennifer Lawrence",
    "Emma Stone",
    "Ryan Reynolds",
    "Gal Gadot",
    "Henry Cavill",
    "Benedict Cumberbatch",
    "Margot Robbie",
    "Dwayne Johnson",
    "Vin Diesel",
    "Jason Momoa",
  ],

  COUNTRIES: [
    "Brazil",
    "Japan",
    "Germany",
    "Egypt",
    "Canada",
    "Australia",
    "Argentina",
    "France",
    "Italy",
    "India",
    "China",
    "Russia",
    "South Africa",
    "Mexico",
    "Spain",
    "Turkey",
    "Sweden",
    "Norway",
    "Greece",
    "Thailand",
    "Vietnam",
    "Indonesia",
    "Colombia",
    "Chile",
    "Peru",
    "Portugal",
    "Netherlands",
    "Belgium",
    "Switzerland",
    "Austria",
    "Poland",
    "Czech Republic",
    "Hungary",
    "Romania",
    "Bulgaria",
    "Croatia",
    "Slovakia",
    "Slovenia",
    "Finland",
    "Denmark",
    "Ireland",
    "New Zealand",
    "Philippines",
    "Malaysia",
    "Singapore",
    "South Korea",
    "North Korea",
    "Saudi Arabia",
  ],

  OBJECTS: [
    "Chair",
    "Table",
    "Laptop",
    "Smartphone",
    "Backpack",
    "Bicycle",
    "Guitar",
    "Piano",
    "Camera",
    "Watch",
    "Sunglasses",
    "Headphones",
    "Microwave",
    "Refrigerator",
    "Television",
    "Sofa",
    "Bed",
    "Desk",
    "Lamp",
    "Book",
    "Pen",
    "Notebook",
    "Mug",
    "Bottle",
    "Glasses",
    "Wallet",
    "Keys",
    "Umbrella",
    "Shoes",
    "Jacket",
    "Hat",
    "Scarf",
    "Gloves",
    "Belt",
    "Ring",
    "Necklace",
    "Bracelet",
    "Earrings",
    "Backpack",
    "Suitcase",
    "Toothbrush",
    "Comb",
    "Mirror",
    "Clock",
    "Calendar",
    "Map",
    "Globe",
    "Calculator",
    "Printer",
    "Router",
    "Speaker",
    "Microphone",
  ],

  JOBS: [
    "Doctor",
    "Engineer",
    "Teacher",
    "Lawyer",
    "Nurse",
    "Architect",
    "Chef",
    "Pilot",
    "Farmer",
    "Scientist",
    "Dentist",
    "Pharmacist",
    "Journalist",
    "Photographer",
    "Designer",
    "Musician",
    "Actor",
    "Director",
    "Writer",
    "Firefighter",
    "Police Officer",
    "Soldier",
    "Mechanic",
    "Electrician",
    "Plumber",
    "Carpenter",
    "Veterinarian",
    "Psychologist",
    "Therapist",
    "Accountant",
    "Banker",
    "Entrepreneur",
    "Salesperson",
    "Marketer",
    "Consultant",
    "Real Estate Agent",
    "Pilot",
    "Flight Attendant",
    "Tour Guide",
    "Translator",
    "Librarian",
    "Scientist",
    "Researcher",
    "Biologist",
    "Chemist",
    "Physicist",
  ],

  YOUTUBE_CHANNELS: [
    "Jovem Nerd",
    "Manual do Mundo",
    "Porta dos Fundos",
    "Felipe Neto",
    "Whindersson Nunes",
    "AuthenticGames",
    "TazerCraft",
    "Parafernalha",
    "Cadê a Chave?",
    "Omelete",
    "5inco Minutos",
    "Coisa de Nerd",
    "T3ddy",
    "LubaTV",
    "PC Siqueira",
    "Fatos Desconhecidos",
    "WatchMojo",
    "PewDiePie",
    "MrBeast",
    "Dude Perfect",
    "Ninja",
    "Markiplier",
    "GameplayRJ",
    "Flow Podcast",
    "Podpah",
  ],

  ANIMALS: [
    "Lion",
    "Tiger",
    "Elephant",
    "Giraffe",
    "Zebra",
    "Kangaroo",
    "Panda",
    "Koala",
    "Cheetah",
    "Leopard",
    "Rhinoceros",
    "Hippopotamus",
    "Crocodile",
    "Alligator",
    "Chimpanzee",
    "Gorilla",
    "Orangutan",
    "Baboon",
    "Wolf",
    "Fox",
    "Bear",
    "Polar Bear",
    "Grizzly Bear",
    "Penguin",
    "Dolphin",
    "Whale",
    "Shark",
    "Octopus",
    "Squid",
    "Eagle",
    "Hawk",
    "Owl",
    "Parrot",
    "Flamingo",
    "Peacock",
    "Swan",
    "Turtle",
    "Tortoise",
    "Frog",
    "Toad",
    "Snake",
    "Lizard",
    "Chameleon",
    "Butterfly",
    "Bee",
    "Ant",
    "Spider",
    "Scorpion",
    "Jellyfish",
    "Starfish",
    "Seahorse",
    "Crab",
    "Lobster",
    "Shrimp",
  ],

  SPORTS: [
    "Soccer",
    "Basketball",
    "Tennis",
    "Baseball",
    "Football",
    "Cricket",
    "Rugby",
    "Hockey",
    "Volleyball",
    "Golf",
    "Swimming",
    "Cycling",
    "Running",
    "Boxing",
    "Wrestling",
    "Martial Arts",
    "Gymnastics",
    "Skiing",
    "Snowboarding",
    "Skateboarding",
    "Surfing",
    "Table Tennis",
    "Badminton",
    "Squash",
    "Archery",
    "Fencing",
    "Rowing",
    "Sailing",
    "Diving",
    "Weightlifting",
    "Triathlon",
    "Pentathlon",
    "Handball",
    "Lacrosse",
    "Field Hockey",
    "Curling",
    "Bobsleigh",
    "Skeleton",
    "Speed Skating",
  ],

  MUSIC: [
    "Beatles",
    "Queen",
    "Michael Jackson",
    "Madonna",
    "Elvis Presley",
    "Beyoncé",
    "Taylor Swift",
    "Adele",
    "Drake",
    "Kanye West",
    "Rihanna",
    "Bruno Mars",
    "Ed Sheeran",
    "Billie Eilish",
    "Dua Lipa",
    "The Weeknd",
    "Lady Gaga",
    "Katy Perry",
    "Justin Bieber",
    "Ariana Grande",
    "Shawn Mendes",
    "Post Malone",
    "Imagine Dragons",
    "Coldplay",
    "Maroon 5",
    "Linkin Park",
    "Nirvana",
    "Foo Fighters",
    "Red Hot Chili Peppers",
    "Green Day",
    "Metallica",
    "AC/DC",
    "Guns N' Roses",
    "U2",
    "Pearl Jam",
    "Radiohead",
  ],
};

export const getAvailableThemes = (): string[] => {
  return Object.keys(THEMES);
};

export const getRandomWord = (theme: string): string => {
  const words = THEMES[theme];
  if (!words) return "Generic Word";
  const randomIndex = Math.floor(Math.random() * words.length);
  return words[randomIndex];
};
